---
title: We are writing a systematic review about VGI
author: Hyesop Shin
date: '2021-02-27'
slug: plans-for-review
categories:
  - VGI
tags:
  - Review
subtitle: ''
summary: ''
authors: []
lastmod: '2021-02-27T12:45:11Z'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# Review
The crowdsourcing project has kicked off a few months ago, but sadly due to COVID19, we haven't been able to work on the fun bits yet. Yes, data crowdsourcing. We know that due to the current circumstances, we have to sadly leave the active work slightly behind and do some desk working first. As a result, we decided to write a review the literature to see what is going on in this discipline.

You may have noticed that we are writing a literature review but *systematically* writing it. What is the difference? Compared to the convential literature review where most authors cite articles and books as per their purpose, a systematic review is written in a more objective way: <br> 
1) formulating questions according to the protocol <br> 
2) showing including and excluding criteria before filtering relevant studies <br> 
3) evaluate the quality of the selected studies 

We understand that by doing a systematic review will enable us maximum information with minimally biased criteria with courtesy to the protocol. Also the transparency is another imporant asset to that.

We set our research aim **to identify and analyse the main components of under-represented participants in various VGI projects and the outlook to encourage diverse participation in future geospatial crowdsourcing**. The main question is shown below:

> Does the contribution of under-represented volunteers (participants) more likely to create diverse outcomes in VGI projects when compared with the socially biased environment?


We have set our research objective and questions, and are currently documenting our selection criteria that looks something like this document (follow [link](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781444316544.app1)).


# Slides
We would be delighted to share more of our current work and receive feedback.

You can click `Present` button in the slide below or simply follow the link (visit [URL](https://docs.google.com/presentation/d/1eEZr-wRSJD1rj31ifno-gVcDnJIfBMmHdUtj7ZWEi9c/view?usp=sharing)).


```{r, eval=T, echo=F}
knitr::include_url('https://docs.google.com/presentation/d/1eEZr-wRSJD1rj31ifno-gVcDnJIfBMmHdUtj7ZWEi9c/view?usp=sharing')
```
Please have a look at the slides for more details and let us know if you have any questions.
